id: P009365
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN6873
  title: ཉི་ནུབ།
  author: ''
  volumes:
    0f126bc3a30844fbab785819b756fc2e:
      image_group_id: I3CN6875
      title: ''
      volume_number: 1
      total_pages: 258
