id: P009365
initial_creation_type: ocr
created_at: 26/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W3CN6873
  title: ཉི་ནུབ།
  author: ''
  volumes:
    0f126bc3a30844fbab785819b756fc2e:
      image_group_id: I3CN6875
      title: ''
      volume_number: 1
      total_pages: 258
      base_file: v001.txt
